name: doccano CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync --dev
    - name: Run migrations
      run: |
        pipenv run wait_for_db
        pipenv run migrate
      working-directory: ./backend
    - name: Lint with flake8
      run: |
        pipenv run flake8
      working-directory: ./backend
    - name: Lint with isort
      run: |
        pipenv run isort
      working-directory: ./backend
    - name: Run tests
      run: |
        pipenv run test
      working-directory: ./backend
